/*! \file jacob_dot.h
\brief Jdot for the LBR4p copy. 
    
  
Given a set of joint variables and joint velocities up to joint number the function 
computes the Jacobian derivatives multiplied by qd with respect to the base frame. 
    
__Example__:<BR> 
     
    
__Known Bugs__:<BR> 
  
    
__TODO__:<BR> 
  
    
__References__:<BR> 
+ 1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
+ 2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
+ 3) Introduction to Robotics, Mechanics and Control - Craig 
+ 4) Modeling, Identification & Control of Robots - Khalil & Dombre 
    
__Authors__:<BR> 
This is an autogenerated function!Code generator written by:Joern Malzahn, Valerio Modugno2014, Technische Universitaet Darmstadt, Germany    
<BR><BR> 
__Copyright Note__: 
  <BR>Copyright  (C) 1993-2015, by Peter I. Corke 
  <BR>Copyright  (C) 2012-2015, by Joern Malzahn 
  
  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
  
  RTB and code generated with RTB is free software: you can redistribute it and/or modify 
  it under the terms of the GNU Lesser General Public License as published by 
  the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version. 
   
  RTB is distributed in the hope that it will be useful, 
  but WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU Lesser General Public License for more details. 
   
  You should have received a copy of the GNU Leser General Public License 
  along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
  
  http://www.petercorke.com 
  
  The code generation module emerged during the work on a project funded by 
  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
  acknowledge the financial support. 
*/
    
/*!\fn void LBR4p_jacob_dot(double jacob_dot[][6], const double* input1, const double* input2);
\param q: vector of generalized coordinates.
\param Angles have to be given in radians!\n
\param qd: vector of the derivatives of generalized coordinates.
\param Jdot: 6x1 vector equal to Jdot*qd.
*/


#ifndef LBR4P_JACOB_DOT_H
#define LBR4P_JACOB_DOT_H

#include "math.h"

void LBR4p_jacob_dot(double jacob_dot[][6], const double* input1, const double* input2);

#endif /*LBR4P_JACOB_DOT_H */
