/*! \file dotprod.h
\brief Compute the dot product of two vectors 
    
  
Given two vectors of length nEl in the input arrays 
input1 and input 2 the function computes the dot product (or scalar product) of both vectors. 
    
__Example__:<BR> 
     
    
__Known Bugs__:<BR> 
  
    
__TODO__:<BR> 
  
    
__References__:<BR> 
+ The C Book: http://publications.gbdirect.co.uk/c_book/ 
    
__Authors__:<BR> 
This is an autogenerated function!Code generator written by:Joern Malzahn (joern.malzahn@tu-dortmund.de)    
<BR><BR> 
__Copyright Note__: 
  <BR>Copyright  (C) 1993-2016, by Peter I. Corke 
  <BR>Copyright  (C) 2012-2016, by Joern Malzahn 
  
  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
  
  RTB and code generated with RTB is free software: you can redistribute it and/or modify 
  it under the terms of the GNU Lesser General Public License as published by 
  the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version. 
   
  RTB is distributed in the hope that it will be useful, 
  but WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU Lesser General Public License for more details. 
   
  You should have received a copy of the GNU Leser General Public License 
  along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
  
  http://www.petercorke.com 
  
  The code generation module emerged during the work on a project funded by 
  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
  acknowledge the financial support. 
*/
    
/*!\fn double dotprod(const double *input1, const double *input2, int nEl)
\param input1: nEl element array of doubles,
\param input2: nEl element array of doubles,
\param nEl: dimension of the two arrays.
*/


#ifndef DOTPROD_H
#define DOTPROD_H

double dotprod(const double *input1, const double *input2, int nEl);

#endif /*DOTPROD_H */
