function jacobn = jacobn(rob,in2)
%% JACOBN - Jacobian with respect to the end-effector coordinate frame of the LBR4pSimple copy arm. 
% ========================================================================= 
%    
%    Jn = jacobn(rob,q) 
%    Jn = rob.jacobn(q) 
%    
%  Description:: 
%    Given a full set of joint variables the function 
%    computes the robot jacobian with respect to the end-effector frame. 
%    
%  Input:: 
%    q:  7-element vector of generalized coordinates. 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Jn:  [6x7] Jacobian matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also fkine,jacob0.
%    
    
% Copyright (C) 1993-2016, by Peter I. Corke 
% Copyright (C) 2012-2016, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    28-Feb-2016 21:53:36

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
q7 = in2(:,7);
t2 = cos(q7);
t3 = cos(q4);
t4 = sin(q5);
t5 = sin(q7);
t6 = t4.*t5;
t7 = cos(q5);
t8 = cos(q6);
t13 = t2.*t7.*t8;
t9 = t6-t13;
t10 = sin(q4);
t11 = sin(q6);
t12 = sin(q3);
t14 = t3.*t9;
t15 = t2.*t10.*t11;
t16 = t14+t15;
t17 = cos(q3);
t18 = t5.*t7;
t19 = t2.*t4.*t8;
t20 = t18+t19;
t21 = sin(q1);
t22 = sin(q2);
t23 = cos(q2);
t24 = t8.*1.518e-1;
t25 = t24+3.9e1./1.0e2;
t26 = cos(q1);
t27 = t10.*t25;
t28 = t3.*t7.*t11.*1.518e-1;
t29 = t27+t28;
t30 = t9.*t10;
t51 = t2.*t3.*t11;
t31 = t30-t51;
t32 = t22.*t31;
t33 = t16.*t17;
t34 = t12.*t20;
t35 = t33+t34;
t52 = t23.*t35;
t36 = t32-t52;
t37 = t12.*t16;
t82 = t17.*t20;
t38 = t37-t82;
t39 = t12.*t29;
t40 = t4.*t11.*t17.*1.518e-1;
t41 = t39+t40;
t42 = t3.*t25;
t49 = t7.*t10.*t11.*1.518e-1;
t43 = t42-t49+2.0./5.0;
t44 = t22.*t43;
t45 = t17.*t29;
t50 = t4.*t11.*t12.*1.518e-1;
t46 = t45-t50;
t47 = t23.*t46;
t48 = t44+t47;
t53 = t2.*t4;
t54 = t5.*t7.*t8;
t55 = t53+t54;
t56 = t3.*t55;
t67 = t5.*t10.*t11;
t57 = t56-t67;
t58 = t2.*t7;
t69 = t4.*t5.*t8;
t59 = t58-t69;
t60 = t21.*t48;
t61 = t26.*t41;
t62 = t60+t61;
t63 = t10.*t55;
t64 = t3.*t5.*t11;
t65 = t63+t64;
t66 = t22.*t65;
t68 = t17.*t57;
t70 = t12.*t59;
t71 = t68+t70;
t77 = t23.*t71;
t72 = t66-t77;
t73 = t12.*t57;
t86 = t17.*t59;
t74 = t73-t86;
t75 = t21.*t41;
t76 = t75-t26.*t48;
t78 = t23.*t43;
t79 = t23.*t31;
t80 = t22.*t35;
t81 = t79+t80;
t83 = t23.*t65;
t84 = t22.*t71;
t85 = t83+t84;
t87 = t8.*t10;
t88 = t3.*t7.*t11;
t89 = t87+t88;
t90 = t3.*t8;
t91 = t90-t7.*t10.*t11;
jacobn = reshape([-t62.*(t21.*t38+t26.*t36)-t76.*(t21.*t36-t26.*t38),-t62.*(t21.*t74+t26.*t72)-t76.*(t21.*t72-t26.*t74),t4.*t10.*t11.*t23.*(3.9e1./1.0e2)+t7.*t11.*t12.*t22.*(3.9e1./1.0e2)+t8.*t10.*t12.*t22.*(2.0./5.0)+t4.*t11.*t17.*t22.*(2.0./5.0)+t3.*t7.*t11.*t12.*t22.*(2.0./5.0)+t3.*t4.*t11.*t17.*t22.*(3.9e1./1.0e2),t81,t85,-t22.*(t17.*t89-t4.*t11.*t12)+t23.*t91,-t48.*t81+t36.*(t78-t22.*t46),-t48.*t85+t72.*(t78-t22.*t46),t4.*t11.*t12.*(-2.0./5.0)+t7.*t11.*t17.*(3.9e1./1.0e2)+t8.*t10.*t17.*(2.0./5.0)-t3.*t4.*t11.*t12.*(3.9e1./1.0e2)+t3.*t7.*t11.*t17.*(2.0./5.0),-t37+t82,-t73+t86,t12.*t89+t4.*t11.*t17,t2.*t4.*t10.*1.518e-1+t3.*t5.*t11.*1.518e-1+t5.*t7.*t10.*(3.9e1./1.0e2)+t2.*t4.*t8.*t10.*(3.9e1./1.0e2)+t5.*t7.*t8.*t10.*1.518e-1,t2.*t3.*t11.*1.518e-1+t2.*t7.*t10.*(3.9e1./1.0e2)-t4.*t5.*t10.*1.518e-1+t2.*t7.*t8.*t10.*1.518e-1-t4.*t5.*t8.*t10.*(3.9e1./1.0e2),t4.*t10.*t11.*(3.9e1./1.0e2),t31,t65,t91,t2.*t7.*1.518e-1-t4.*t5.*(3.9e1./1.0e2)+t2.*t7.*t8.*(3.9e1./1.0e2)-t4.*t5.*t8.*1.518e-1,t2.*t4.*(-3.9e1./1.0e2)-t5.*t7.*1.518e-1-t2.*t4.*t8.*1.518e-1-t5.*t7.*t8.*(3.9e1./1.0e2),t7.*t11.*(3.9e1./1.0e2),t20,t59,t4.*t11,t5.*t11.*1.518e-1,t2.*t11.*1.518e-1,0.0,-t2.*t11,t5.*t11,t8,t2.*1.518e-1,t5.*(-1.518e-1),0.0,t5,t2,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6, 7]);
