function jacob0 = jacob0(rob,in2)
%% JACOB0 - Jacobian with respect to the base coordinate frame of the Puma 560 copy arm. 
% ========================================================================= 
%    
%    J0 = jacob0(rob,q) 
%    J0 = rob.jacob0(q) 
%    
%  Description:: 
%    Given a full set of joint variables the function 
%    computes the robot jacobian with respect to the base frame. 
%    
%  Input:: 
%    q:  6-element vector of generalized coordinates. 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    J0:  [6x6] Jacobian matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also fkine,jacobn.
%    
    
% Copyright (C) 1993-2014, by Peter I. Corke 
% Copyright (C) 2012-2014, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    22-Nov-2014 18:14:00

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
t2 = cos(q1);
t3 = sin(q1);
t4 = sin(q4);
t5 = cos(q4);
t6 = cos(q2);
t7 = cos(q3);
t8 = sin(q2);
t9 = sin(q3);
t19 = t2.*t6.*t7;
t20 = t2.*t8.*t9;
t10 = t19-t20;
t11 = sin(q6);
t12 = q2+q3;
t13 = cos(t12);
t14 = cos(q5);
t15 = cos(q6);
t16 = sin(t12);
t17 = sin(q5);
t18 = t3.*t5;
t21 = t4.*t10;
t22 = t18+t21;
t23 = t3.*t4;
t31 = t5.*t10;
t24 = t23-t31;
t25 = t14.*t24;
t26 = t2.*t6.*t9;
t27 = t2.*t7.*t8;
t28 = t26+t27;
t29 = t17.*t28;
t30 = t25+t29;
t32 = t17.*t24;
t39 = t14.*t28;
t33 = t32-t39;
t34 = t11.*t22;
t35 = t15.*t30;
t36 = t34+t35;
t37 = t15.*t22;
t44 = t11.*t30;
t38 = t37-t44;
t40 = t14.*2.03e-2;
t41 = t5.*t17.*4.318e-1;
t42 = t15.*t17.*2.03e-2;
t43 = t4.*t11.*4.318e-1;
t45 = t11.*t17.*2.03e-2;
t46 = t3.*t6.*t7;
t56 = t3.*t8.*t9;
t47 = t46-t56;
t48 = t5.*t11.*t13.*2.03e-2;
t49 = t5.*t6.*t11.*4.318e-1;
t50 = t4.*t13.*t14.*t15.*2.03e-2;
t51 = t4.*t6.*t14.*t15.*4.318e-1;
t52 = t4.*t8.*t9.*t11.*1.5005e-1;
t53 = t5.*t6.*t7.*t14.*t15.*1.5005e-1;
t103 = t5.*t11.*t16.*4.318e-1;
t104 = t4.*t14.*t15.*t16.*4.318e-1;
t105 = t4.*t6.*t7.*t11.*1.5005e-1;
t106 = t6.*t9.*t15.*t17.*1.5005e-1;
t107 = t7.*t8.*t15.*t17.*1.5005e-1;
t108 = t5.*t8.*t9.*t14.*t15.*1.5005e-1;
t54 = t48+t49+t50+t51+t52+t53-t103-t104-t105-t106-t107-t108;
t55 = t2.*t5;
t84 = t4.*t47;
t57 = t55-t84;
t58 = t2.*t4;
t59 = t3.*t6.*t9;
t60 = t3.*t7.*t8;
t61 = t59+t60;
t62 = t17.*t61;
t63 = t5.*t13.*t15.*2.03e-2;
t64 = t5.*t6.*t15.*4.318e-1;
t65 = t4.*t11.*t14.*t16.*4.318e-1;
t66 = t4.*t8.*t9.*t15.*1.5005e-1;
t67 = t6.*t9.*t11.*t17.*1.5005e-1;
t68 = t7.*t8.*t11.*t17.*1.5005e-1;
t69 = t5.*t8.*t9.*t11.*t14.*1.5005e-1;
t112 = t5.*t15.*t16.*4.318e-1;
t113 = t4.*t11.*t13.*t14.*2.03e-2;
t114 = t4.*t6.*t7.*t15.*1.5005e-1;
t115 = t4.*t6.*t11.*t14.*4.318e-1;
t116 = t5.*t6.*t7.*t11.*t14.*1.5005e-1;
t70 = t63+t64+t65+t66+t67+t68+t69-t112-t113-t114-t115-t116;
t71 = t5.*(t46-t56);
t72 = t58+t71;
t73 = t6.*t9.*t14.*1.5005e-1;
t74 = t7.*t8.*t14.*1.5005e-1;
t75 = t4.*t6.*t17.*4.318e-1;
t76 = t5.*t6.*t7.*t17.*1.5005e-1;
t77 = t4.*t6.*t7.*t17.*2.03e-2;
t117 = t4.*t6.*t9.*t17.*4.318e-1;
t118 = t4.*t7.*t8.*t17.*4.318e-1;
t119 = t5.*t8.*t9.*t17.*1.5005e-1;
t120 = t4.*t8.*t9.*t17.*2.03e-2;
t78 = t73+t74+t75+t76+t77-t117-t118-t119-t120;
t79 = t17.*t72;
t80 = t14.*t61;
t81 = t79+t80;
t82 = t7.*t14.*4.318e-1;
t126 = t5.*t9.*t17.*4.318e-1;
t83 = t40+t41+t82-t126;
t85 = t11.*t57;
t91 = t14.*t72;
t86 = t62-t91;
t87 = t7.*t15.*t17.*4.318e-1;
t88 = t5.*t9.*t14.*t15.*4.318e-1;
t101 = t5.*t14.*t15.*4.318e-1;
t123 = t4.*t9.*t11.*4.318e-1;
t89 = t42+t43+t87+t88-t101-t123;
t90 = t15.*t57;
t92 = t4.*t15.*4.318e-1;
t93 = t5.*t11.*t14.*4.318e-1;
t94 = t4.*t9.*t15.*4.318e-1;
t95 = t7.*t11.*t17.*4.318e-1;
t96 = t5.*t9.*t11.*t14.*4.318e-1;
t97 = t11.*t86;
t98 = t90+t97;
t99 = t40+t41;
t148 = t15.*t86;
t100 = t85-t148;
t102 = -t45+t92+t93;
t109 = t13.*t17;
t110 = t5.*t14.*t16;
t111 = t109+t110;
t121 = t15.*t111;
t132 = t4.*t11.*t16;
t122 = t121-t132;
t124 = t13.*t14;
t131 = t5.*t16.*t17;
t125 = t124-t131;
t127 = t11.*t111;
t128 = t4.*t15.*t16;
t129 = t127+t128;
t130 = t45-t92-t93+t94+t95+t96;
t133 = t42+t43-t101;
t134 = t4.*t15;
t135 = t5.*t11.*t14;
t136 = t134+t135;
t137 = t4.*t11;
t149 = t5.*t14.*t15;
t138 = t137-t149;
t139 = t5.*t11;
t140 = t4.*t14.*t15;
t141 = t139+t140;
t142 = t36.*t141;
t143 = t5.*t15;
t174 = t4.*t11.*t14;
t144 = t143-t174;
t145 = t38.*t144;
t146 = t4.*t17.*t33;
t147 = t142+t145+t146;
t150 = t9.*t138;
t179 = t7.*t15.*t17;
t151 = t150-t179;
t152 = t6.*t151;
t153 = t7.*t138;
t154 = t9.*t15.*t17;
t155 = t153+t154;
t156 = t8.*t155;
t157 = t152+t156;
t158 = t7.*t14;
t176 = t5.*t9.*t17;
t159 = t158-t176;
t160 = t9.*t14;
t161 = t5.*t7.*t17;
t162 = t160+t161;
t177 = t6.*t159;
t178 = t8.*t162;
t163 = t177-t178;
t164 = t11.*(t62-t91);
t165 = t90+t164;
t166 = t9.*t136;
t167 = t7.*t11.*t17;
t168 = t166+t167;
t169 = t6.*t168;
t170 = t7.*t136;
t180 = t9.*t11.*t17;
t171 = t170-t180;
t172 = t8.*t171;
t173 = t169+t172;
t175 = -t100.*t141-t144.*t165-t4.*t17.*t81;
t181 = t129.*t144;
t182 = t4.*t17.*t125;
t183 = t181+t182-t122.*t141;
jacob0 = reshape([-t36.*t54-t38.*t70-t33.*t78,t54.*(t85-t15.*(t62-t14.*(t58+t5.*t47)))+t78.*t81+t70.*t98,t54.*t122-t70.*t129-t78.*t125,t36.*t157+t33.*t163+t38.*t173,-t81.*t163-t100.*t157-t165.*t173,-t122.*t157+t125.*t163+t129.*t173,t38.*(t45+t94+t95+t96-t4.*t15.*4.318e-1-t5.*t11.*t14.*4.318e-1)+t33.*t83-t36.*t89,-t81.*t83+t89.*t100-t98.*t130,t83.*t125+t89.*t122+t129.*t130,t147,t175,t183,t33.*t99-t38.*t102-t36.*(t42+t43-t5.*t14.*t15.*4.318e-1),-t81.*t99+t100.*t133+t102.*t165,t99.*t125-t102.*t129+t122.*t133,t147,t175,t183,0.0,0.0,0.0,t14.*t33+t11.*t17.*t38-t15.*t17.*t36,-t14.*t81+t15.*t17.*t100-t11.*t17.*t165,t14.*t125+t15.*t17.*t122+t11.*t17.*t129,0.0,0.0,0.0,t11.*t36+t15.*t38,-t11.*t100-t15.*t165,-t11.*t122+t15.*t129,0.0,0.0,0.0,t33,-t79-t80,t125],[6, 6]);
