function [] = genmfunJdot(CGen)

%% Does robot class exist?
if ~exist(fullfile(CGen.robjpath,[CGen.getrobfname,'.m']),'file')
    CGen.logmsg([datestr(now),'\tCreating ',CGen.getrobfname,' m-constructor ']);
    CGen.createmconstructor;
    CGen.logmsg('\t%s\n',' done!');
end

%% Forward kinematics up to tool center point
CGen.logmsg([datestr(now),'\tGenerating Jdot: ']);
symname = 'jacob_dot';
fname = fullfile(CGen.sympath,[symname,'.mat']);

if exist(fname,'file')
    tmpStruct = load(fname);
else
    error ('genmfunJdot:SymbolicsNotFound','Save symbolic expressions to disk first!')
end

funfilename = fullfile(CGen.robjpath,[symname,'.m']);
[q,qd] = CGen.rob.gencoords;

matlabFunction(tmpStruct.(symname),'file',funfilename,...              % generate function m-file
    'outputs', {symname},...
    'vars', {'rob',q,qd});
hStruct = createHeaderStructJdot(CGen.rob,symname);                 % replace autogenerated function header
replaceheader(CGen,hStruct,funfilename);
CGen.logmsg('\t%s\n',' done!');


end

%% Definition of the header contents for each generated file
function hStruct = createHeaderStructJdot(rob,fname)
[~,hStruct.funName] = fileparts(fname);
hStruct.shortDescription = ['Jdot for the ',rob.name,'.'];
hStruct.calls = {['Jdot = ',hStruct.funName,'(rob,q,qd)'],...
    ['Jdot = rob.',hStruct.funName,'(q,qd)']};
hStruct.detailedDescription = {'Given a set of joint variables and joint velocities up to joint number the function',...
    'computes the Jacobian derivatives multiplied by qd with respect to the base frame.'};
hStruct.inputs = {'q: vector of generalized coordinates.',...
    'Angles have to be given in radians!\n'...
    'qd: vector of the derivatives of generalized coordinates.'};
hStruct.outputs = {'Jdot: 6x1 vector equal to Jdot*qd.'};
hStruct.references = {'1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar',...
    '2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano',...
    '3) Introduction to Robotics, Mechanics and Control - Craig',...
    '4) Modeling, Identification & Control of Robots - Khalil & Dombre'};
hStruct.authors = {'This is an autogenerated function!',...
    'Code generator written by:',...
    'Joern Malzahn, Valerio Modugno',...
    '2014, Technische Universitaet Darmstadt, Germany'};
hStruct.seeAlso = {rob.name};
end
