function jacob0 = jacob0(rob,in2)
%% JACOB0 - Jacobian with respect to the base coordinate frame of the Jaco copy arm. 
% ========================================================================= 
%    
%    J0 = jacob0(rob,q) 
%    J0 = rob.jacob0(q) 
%    
%  Description:: 
%    Given a full set of joint variables the function 
%    computes the robot jacobian with respect to the base frame. 
%    
%  Input:: 
%    q:  6-element vector of generalized coordinates. 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    J0:  [6x6] Jacobian matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also fkine,jacobn.
%    
    
% Copyright (C) 1993-2015, by Peter I. Corke 
% Copyright (C) 2012-2015, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    17-Aug-2015 15:55:13

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
t2 = pi.*(1.1e1./3.6e1);
t3 = cos(t2);
t4 = cos(q1);
t5 = sin(t2);
t6 = sin(q2);
t7 = sin(q3);
t8 = cos(q2);
t9 = cos(q3);
t10 = sin(q4);
t11 = sin(q1);
t12 = cos(q4);
t13 = sin(q5);
t14 = t3.^2;
t15 = cos(q5);
t16 = pi.*(1.0./1.8e1);
t17 = q6+t16;
t18 = cos(t17);
t19 = sin(t17);
t20 = t15.*t18;
t26 = t3.*t13.*t19;
t21 = t20-t26;
t22 = t13.*t18;
t23 = t3.*t15.*t19;
t24 = t22+t23;
t25 = t5.^2;
t27 = t3.*t10.*t24;
t28 = t10.*t19.*t25;
t42 = t12.*t21;
t29 = t27+t28-t42;
t44 = t3.*t19;
t30 = t22+t23-t44;
t31 = t3.*8.376447865216925e-2;
t32 = t14.*2.105822393260846e-1;
t33 = t15.*t25.*2.105822393260846e-1;
t34 = t31+t32+t33+2.491822393260846e-1;
t35 = t10.*6.035866797516693e15;
t36 = t3.*t10.*1.517404951295679e16;
t54 = t12.*t13.*1.517404951295679e16;
t55 = t3.*t10.*t15.*1.517404951295679e16;
t37 = t35+t36-t54-t55;
t38 = t10.*t21;
t39 = t3.*t12.*t24;
t40 = t12.*t19.*t25;
t41 = t38+t39+t40;
t43 = t9.*t29;
t128 = t5.*t7.*t30;
t45 = t43-t128;
t46 = t8.*t45;
t47 = t7.*t29;
t48 = t5.*t9.*t30;
t49 = t47+t48;
t50 = t6.*t49;
t51 = t46+t50;
t52 = t6.*(4.1e1./1.0e2);
t53 = t7.*t34;
t56 = t5.*t9.*t37.*1.387778780781446e-17;
t57 = t53+t56;
t58 = t8.*t57;
t59 = t9.*t34;
t93 = t5.*t7.*t37.*1.387778780781446e-17;
t60 = t59-t93;
t94 = t6.*t60;
t61 = t52+t58-t94;
t62 = t5.*t10.*t13.*2.105822393260846e-1;
t63 = t3.*2.105822393260846e-1;
t64 = t63+8.376447865216925e-2;
t65 = t5.*t12.*t64;
t96 = t3.*t5.*t12.*t15.*2.105822393260846e-1;
t66 = t62+t65-t96-9.8e-3;
t67 = t4.*t8.*t9.*t12;
t68 = t4.*t6.*t7.*t12;
t80 = t10.*t11;
t69 = t67+t68-t80;
t70 = t3.*t11.*t12;
t71 = t4.*t5.*t6.*t9;
t72 = t3.*t4.*t8.*t9.*t10;
t73 = t3.*t4.*t6.*t7.*t10;
t81 = t4.*t5.*t7.*t8;
t74 = t70+t71+t72+t73-t81;
t75 = t5.*t11.*t12;
t76 = t3.*t4.*t7.*t8;
t77 = t4.*t5.*t6.*t7.*t10;
t78 = t4.*t5.*t8.*t9.*t10;
t115 = t3.*t4.*t6.*t9;
t79 = t75+t76+t77+t78-t115;
t82 = t15.*t19;
t83 = t3.*t13.*t18;
t84 = t82+t83;
t85 = t13.*t19;
t87 = t3.*t15.*t18;
t86 = t85-t87;
t88 = t12.*t84;
t89 = t10.*t18.*t25;
t102 = t3.*t10.*t86;
t90 = t88+t89-t102;
t91 = t3.*t18;
t92 = t85-t87+t91;
t95 = t4.*t61;
t97 = t11.*t66;
t98 = t95+t97;
t99 = t10.*t84;
t100 = t3.*t12.*t86;
t172 = t12.*t18.*t25;
t101 = t99+t100-t172;
t103 = t9.*t90;
t104 = t5.*t7.*t92;
t105 = t103+t104;
t106 = t8.*t105;
t107 = t7.*t90;
t120 = t5.*t9.*t92;
t108 = t107-t120;
t109 = t6.*t108;
t110 = t106+t109;
t111 = t4.*t66;
t147 = t11.*t61;
t112 = t111-t147;
t113 = t15.*t69;
t121 = t13.*t74;
t114 = t113-t121;
t116 = t5.*t79;
t117 = t3.*t13.*t69;
t118 = t3.*t15.*t74;
t119 = t116+t117+t118;
t122 = t19.*t114;
t123 = t18.*t119;
t124 = t122+t123;
t125 = t5.*t13.*t69;
t126 = t5.*t15.*t74;
t135 = t3.*t79;
t127 = t125+t126-t135;
t129 = t8.*t60;
t130 = t6.*t57;
t201 = t8.*(4.1e1./1.0e2);
t131 = t129+t130-t201;
t132 = t18.*t114;
t134 = t19.*t119;
t133 = t132-t134;
t136 = pi.*(4.0./9.0);
t137 = cos(t136);
t138 = sin(q6);
t139 = sin(t136);
t140 = cos(q6);
t141 = sqrt(2.0);
t255 = pi.*(5.0./3.6e1);
t142 = q6-t255;
t143 = t140.*t141.*5.264555983152115e-2;
t144 = t11.*t41;
t145 = t4.*t51;
t146 = t144+t145;
t148 = t112.*t146;
t149 = t4.*t41;
t289 = t11.*t51;
t150 = t149-t289;
t151 = t4.*t10;
t152 = t8.*t9.*t11.*t12;
t153 = t6.*t7.*t11.*t12;
t154 = t151+t152+t153;
t155 = t5.*t6.*t9.*t11;
t156 = t3.*t6.*t7.*t10.*t11;
t157 = t3.*t8.*t9.*t10.*t11;
t166 = t3.*t4.*t12;
t167 = t5.*t7.*t8.*t11;
t158 = t155+t156+t157-t166-t167;
t290 = t98.*t150;
t159 = t148-t290;
t160 = t3.*t7.*t8.*t11;
t161 = t5.*t6.*t7.*t10.*t11;
t162 = t5.*t8.*t9.*t10.*t11;
t180 = t4.*t5.*t12;
t181 = t3.*t6.*t9.*t11;
t163 = t160+t161+t162-t180-t181;
t164 = t5.*t163;
t165 = t3.*t13.*t154;
t168 = t3.*t15.*t158;
t169 = t164+t165+t168;
t170 = t15.*t154;
t199 = t13.*t158;
t171 = t170-t199;
t173 = t4.*t101;
t174 = t11.*t110;
t175 = t173+t174;
t176 = t98.*t175;
t177 = t11.*t101;
t276 = t4.*t110;
t178 = t177-t276;
t277 = t112.*t178;
t179 = t176-t277;
t182 = t6.*t9.*t14.*9.8e-3;
t183 = t6.*t9.*t15.*9.8e-3;
t184 = t8.*t9.*t13.*t14.*8.376447865216925e-2;
t185 = t7.*t8.*t14.*t15.*9.8e-3;
t186 = t6.*t7.*t13.*t14.*8.376447865216925e-2;
t187 = t5.*t6.*t9.*t10.*t13.*2.491822393260846e-1;
t188 = t5.*t6.*t7.*t12.*t13.*9.8e-3;
t189 = t3.*t5.*t6.*t9.*t12.*2.491822393260846e-1;
t190 = t3.*t5.*t6.*t12.*t15.*(4.1e1./1.0e2);
t191 = t5.*t8.*t9.*t12.*t13.*9.8e-3;
t192 = t5.*t7.*t8.*t12.*t15.*8.376447865216925e-2;
t193 = t3.*t5.*t6.*t9.*t10.*t13.*8.376447865216925e-2;
t194 = t3.*t5.*t6.*t7.*t10.*t15.*9.8e-3;
t195 = t3.*t5.*t8.*t9.*t10.*t15.*9.8e-3;
t196 = t3.*t5.*t7.*t8.*t12.*t15.*2.491822393260846e-1;
t262 = t6.*t7.*t13.*8.376447865216925e-2;
t263 = t7.*t8.*t14.*9.8e-3;
t264 = t8.*t9.*t13.*8.376447865216925e-2;
t265 = t7.*t8.*t15.*9.8e-3;
t266 = t5.*t6.*t10.*t13.*(4.1e1./1.0e2);
t267 = t3.*t5.*t6.*t12.*(4.1e1./1.0e2);
t268 = t6.*t9.*t14.*t15.*9.8e-3;
t269 = t5.*t7.*t8.*t10.*t13.*2.491822393260846e-1;
t270 = t3.*t5.*t8.*t9.*t10.*9.8e-3;
t271 = t3.*t5.*t7.*t8.*t12.*2.491822393260846e-1;
t272 = t3.*t5.*t6.*t7.*t10.*9.8e-3;
t273 = t5.*t6.*t9.*t12.*t15.*8.376447865216925e-2;
t274 = t3.*t5.*t7.*t8.*t10.*t13.*8.376447865216925e-2;
t275 = t3.*t5.*t6.*t9.*t12.*t15.*2.491822393260846e-1;
t197 = t182+t183+t184+t185+t186+t187+t188+t189+t190+t191+t192+t193+t194+t195+t196-t262-t263-t264-t265-t266-t267-t268-t269-t270-t271-t272-t273-t274-t275;
t198 = t19.*t169;
t227 = t18.*t171;
t200 = t198-t227;
t202 = t51.*t131;
t203 = t6.*t45;
t311 = t8.*t49;
t204 = t203-t311;
t312 = t61.*t204;
t205 = t202-t312;
t206 = t5.*t13.*t154;
t207 = t5.*t15.*t158;
t231 = t3.*t163;
t208 = t206+t207-t231;
t209 = t7.*t15.*(4.1e1./1.0e2);
t210 = t7.*t14.*(4.1e1./1.0e2);
t211 = t5.*t12.*t13.*2.491822393260846e-1;
t212 = t5.*t10.*t15.*8.376447865216925e-2;
t213 = t3.*t5.*t9.*t10.*(4.1e1./1.0e2);
t214 = t3.*t5.*t12.*t13.*8.376447865216925e-2;
t215 = t3.*t5.*t10.*t15.*2.491822393260846e-1;
t301 = t3.*t5.*t10.*2.491822393260846e-1;
t302 = t7.*t14.*t15.*(4.1e1./1.0e2);
t303 = t5.*t9.*t12.*t13.*(4.1e1./1.0e2);
t304 = t3.*t5.*t9.*t10.*t15.*(4.1e1./1.0e2);
t216 = t209+t210+t211+t212+t213+t214+t215-t301-t302-t303-t304;
t217 = t110.*t131;
t218 = t6.*t105;
t305 = t8.*t108;
t219 = t218-t305;
t306 = t61.*t219;
t220 = t217-t306;
t221 = t18.*t169;
t222 = t19.*t171;
t223 = t221+t222;
t224 = t60.*t105;
t225 = t57.*t108;
t226 = t224+t225;
t228 = t49.*t57;
t229 = t45.*t60;
t230 = t228+t229;
t232 = t12.*t13.*5.985157547606936e15;
t233 = t10.*t15.*2.011955599172231e15;
t234 = t3.*t12.*t13.*2.011955599172231e15;
t235 = t3.*t10.*t15.*5.985157547606936e15;
t317 = t3.*t10.*5.985157547606936e15;
t236 = t232+t233+t234+t235-t317;
t237 = t15.*t137.*t140.*6.035866797516693e15;
t238 = t15.*t138.*t139.*6.035866797516693e15;
t239 = t13.*t139.*t140.*1.517404951295679e16;
t240 = t3.*t15.*t137.*t140.*1.517404951295679e16;
t241 = t3.*t15.*t138.*t139.*1.517404951295679e16;
t242 = t3.*t13.*t139.*t140.*6.035866797516693e15;
t318 = t13.*t137.*t138.*1.517404951295679e16;
t319 = t3.*t137.*t140.*1.517404951295679e16;
t320 = t3.*t138.*t139.*1.517404951295679e16;
t321 = t3.*t13.*t137.*t138.*6.035866797516693e15;
t243 = t237+t238+t239+t240+t241+t242-t318-t319-t320-t321;
t244 = t15.*t137.*t138.*6.035866797516693e15;
t245 = t13.*t137.*t140.*1.517404951295679e16;
t246 = t13.*t138.*t139.*1.517404951295679e16;
t247 = t3.*t139.*t140.*1.517404951295679e16;
t248 = t3.*t15.*t137.*t138.*1.517404951295679e16;
t249 = t3.*t13.*t137.*t140.*6.035866797516693e15;
t250 = t3.*t13.*t138.*t139.*6.035866797516693e15;
t322 = t15.*t139.*t140.*6.035866797516693e15;
t323 = t3.*t137.*t138.*1.517404951295679e16;
t324 = t3.*t15.*t139.*t140.*1.517404951295679e16;
t251 = t244+t245+t246+t247+t248+t249+t250-t322-t323-t324;
t252 = pi.*(7.0./1.8e1);
t253 = cos(t252);
t254 = t253+1.0;
t256 = cos(t142);
t257 = t256.*1.052911196630423e-1;
t258 = t138.*t141.*5.264555983152115e-2;
t259 = sin(t142);
t260 = t259.*1.052911196630423e-1;
t261 = t143+t258+t260;
t278 = t5.*t8.*t9;
t279 = t5.*t6.*t7;
t280 = t3.*t7.*t8.*t10;
t288 = t3.*t6.*t9.*t10;
t281 = t278+t279+t280-t288;
t282 = q2-q3;
t283 = sin(t282);
t284 = t3.*t8.*t9;
t285 = t3.*t6.*t7;
t286 = t5.*t6.*t9.*t10;
t291 = t5.*t7.*t8.*t10;
t287 = t284+t285+t286-t291;
t292 = t5.*t287;
t293 = t3.*t12.*t13.*t283;
t308 = t3.*t15.*t281;
t294 = t292+t293-t308;
t295 = t13.*t281;
t296 = t12.*t15.*t283;
t297 = t295+t296;
t298 = t3.*t287;
t299 = t5.*t15.*t281;
t316 = t5.*t12.*t13.*t283;
t300 = t298+t299-t316;
t307 = t19.*t297;
t309 = t18.*t294;
t310 = t307+t309;
t313 = t19.*t294;
t315 = t18.*t297;
t314 = t313-t315;
t325 = t143+t257-t258;
t326 = t15.*t25;
t327 = t14+t326;
t328 = t12.*t13;
t329 = t3.*t10.*t15;
t342 = t3.*t10;
t330 = t328+t329-t342;
t331 = t101.*t124;
t332 = t41.*t133;
t333 = t10.*t13;
t334 = t3.*t12;
t350 = t3.*t12.*t15;
t335 = t333+t334-t350;
t336 = t5.*t127.*t335;
t337 = pi.*(5.0./9.0);
t338 = q6+t337;
t339 = cos(t338);
t340 = sin(t338);
t341 = t9.*t327;
t343 = t5.*t7.*t330;
t344 = t341+t343;
t345 = t8.*t344;
t346 = t7.*t327;
t362 = t5.*t9.*t330;
t347 = t346-t362;
t348 = t6.*t347;
t349 = t345+t348;
t351 = t41.*t200;
t352 = t13.*t339;
t353 = t3.*t15.*t340;
t354 = t352+t353;
t355 = t5.*t354;
t365 = t3.*t5.*t340;
t356 = t355-t365;
t357 = t13.*t340;
t364 = t3.*t15.*t339;
t358 = t357-t364;
t359 = t5.*t358;
t360 = t3.*t5.*t339;
t361 = t359+t360;
t363 = t101.*t310;
jacob0 = reshape([-t133.*t159+t124.*t179-t127.*t197,-t159.*t200-t179.*t223+t197.*t208,t179.*t310+t197.*t300+t314.*(t148-t290),-t124.*t219+t127.*t349+t133.*(t203-t311),-t208.*t349+t200.*(t203-t311)+t223.*(t218-t305),-t204.*t314-t219.*t310-t300.*t349,t133.*t205-t127.*t216-t124.*t220,t200.*t205+t208.*t216+t220.*t223,t216.*t300-t205.*t314-t220.*t310,t331+t332+t336,t351-t101.*t223-t5.*t208.*t335,t363-t41.*t314-t5.*t300.*t335,t124.*t226-t133.*t230+t5.*t127.*t236.*4.163336342344337e-17,-t200.*t230-t223.*t226-t5.*t208.*t236.*4.163336342344337e-17,t226.*t310+t230.*t314-t5.*t236.*t300.*4.163336342344337e-17,-t331-t332-t336,-t351+t101.*t223+t5.*t208.*t335,-t363+t41.*t314+t5.*t300.*t335,t5.*t124.*t243.*1.387778780781446e-17-t5.*t133.*t251.*1.387778780781446e-17+t13.*t127.*t254.*4.188223932608463e-2,t5.*t200.*t251.*(-1.387778780781446e-17)-t5.*t223.*t243.*1.387778780781446e-17-t13.*t208.*t254.*4.188223932608463e-2,t5.*t243.*t310.*1.387778780781446e-17-t13.*t254.*t300.*4.188223932608463e-2+t5.*t251.*t314.*1.387778780781446e-17,t127.*t327+t124.*t356-t133.*t361,-t208.*t327-t200.*t361-t223.*t356,-t300.*t327+t310.*t356+t314.*t361,-t124.*t261-t133.*(t143+t257-t138.*t141.*5.264555983152115e-2),t223.*t261-t200.*t325,-t261.*t310+t314.*t325,t3.*t127-t5.*t18.*t124+t5.*t19.*t133,-t3.*t208+t5.*t19.*t200+t5.*t18.*t223,-t3.*t300-t5.*t18.*t310-t5.*t19.*t314,0.0,0.0,0.0,t127,-t206-t207+t231,-t298-t299+t316],[6, 6]);
