function jacob_dot = jacob_dot(rob,in2,in3)
%% JACOB_DOT - Jdot for the Jaco copy. 
% ========================================================================= 
%    
%    Jdot = jacob_dot(rob,q,qd) 
%    Jdot = rob.jacob_dot(q,qd) 
%    
%  Description:: 
%    Given a set of joint variables and joint velocities up to joint number the function 
%    computes the Jacobian derivatives multiplied by qd with respect to the base frame. 
%    
%  Input:: 
%    q: vector of generalized coordinates. 
%    Angles have to be given in radians!\n 
%    qd: vector of the derivatives of generalized coordinates. 
%    
%  Output:: 
%    Jdot: 6x1 vector equal to Jdot*qd. 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn, Valerio Modugno 
%    2014, Technische Universitaet Darmstadt, Germany 
%    
%  See also Jaco copy.
%    
    
% Copyright (C) 1993-2015, by Peter I. Corke 
% Copyright (C) 2012-2015, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    12-Aug-2015 17:58:33

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
qd1 = in3(:,1);
qd2 = in3(:,2);
qd3 = in3(:,3);
qd4 = in3(:,4);
qd5 = in3(:,5);
qd6 = in3(:,6);
t2 = pi.*(1.1e1./3.6e1);
t3 = sin(t2);
t4 = pi.*(1.0./2.0);
t5 = q3+t4;
t6 = q2-t4;
t7 = sin(t5);
t8 = cos(t6);
t9 = cos(t5);
t10 = sin(t6);
t11 = cos(t2);
t12 = qd1.*t8.*t9;
t13 = qd1.*t7.*t10;
t14 = qd4+t12+t13;
t15 = sin(q4);
t16 = qd1.*t7.*t8;
t21 = qd1.*t9.*t10;
t17 = t16-t21;
t18 = cos(q4);
t19 = qd2-qd3;
t20 = sin(q5);
t22 = cos(q5);
t23 = t3.*t14;
t24 = t11.*t15.*t17;
t29 = t11.*t18.*t19;
t25 = t23+t24-t29;
t26 = t17.*t18;
t27 = t15.*t19;
t28 = t26+t27;
t30 = t20.*t25.*2.105822393260846e-1;
t38 = t22.*t28.*2.105822393260846e-1;
t31 = t30-t38;
t32 = t11.*t14;
t33 = t3.*t18.*t19;
t39 = t3.*t15.*t17;
t34 = qd5+t32+t33-t39;
t35 = t11.*t22.*t25.*2.105822393260846e-1;
t36 = t11.*t20.*t28.*2.105822393260846e-1;
t40 = t3.*t34.*2.105822393260846e-1;
t37 = t35+t36-t40;
t41 = t20.*t37;
t42 = t17.*t18.*8.376447865216925e-2;
t43 = t15.*t19.*8.376447865216925e-2;
t45 = t11.*t22.*t31;
t44 = t41+t42+t43-t45;
t46 = t3.*t44;
t47 = t3.*t11.*t31;
t48 = t46+t47;
t49 = qd3.*2.491822393260846e-1;
t50 = t22.*t37;
t51 = t3.*t14.*8.376447865216925e-2;
t52 = t11.*t15.*t17.*8.376447865216925e-2;
t53 = t11.*t20.*t31;
t59 = t11.*t18.*t19.*8.376447865216925e-2;
t54 = t50+t51+t52+t53-t59;
t55 = t18.*t54;
t56 = t3.^2;
t57 = t15.*t31.*t56;
t125 = qd2.*2.491822393260846e-1;
t126 = t11.*t15.*t44;
t58 = t49+t55+t57-t125-t126;
t60 = sin(q1);
t61 = t8.*t9;
t62 = t7.*t10;
t63 = t61+t62;
t64 = t7.*t8;
t66 = t9.*t10;
t65 = t64-t66;
t67 = cos(q1);
t68 = t7.*t10.*t67;
t69 = t8.*t9.*t67;
t70 = t68+t69;
t71 = t7.*t8.*t67;
t100 = t9.*t10.*t67;
t72 = t71-t100;
t73 = t11.*t63;
t113 = t3.*t15.*t65;
t74 = t73-t113;
t75 = t11.*t74;
t76 = t3.*t63;
t77 = t11.*t15.*t65;
t78 = t76+t77;
t79 = t3.*t22.*t78;
t80 = t3.*t18.*t20.*t65;
t81 = t75+t79+t80;
t82 = t8.*t9.*t60;
t83 = t7.*t10.*t60;
t84 = t82+t83;
t85 = t7.*t8.*t60;
t87 = t9.*t10.*t60;
t86 = t85-t87;
t88 = t11.*t86;
t89 = t3.*t18.*t67;
t90 = t3.*t15.*t84;
t91 = t88+t89+t90;
t92 = t11.*t91;
t93 = t15.*t67;
t117 = t18.*t84;
t94 = t93-t117;
t95 = t3.*t20.*t94;
t96 = t11.*t18.*t67;
t97 = t11.*t15.*t84;
t118 = t3.*t86;
t98 = t96+t97-t118;
t119 = t3.*t22.*t98;
t99 = t92+t95-t119;
t101 = t11.*t72;
t102 = t3.*t15.*t70;
t114 = t3.*t18.*t60;
t103 = t101+t102-t114;
t104 = t11.*t103;
t105 = t15.*t60;
t106 = t18.*t70;
t107 = t105+t106;
t108 = t3.*t72;
t109 = t11.*t18.*t60;
t116 = t11.*t15.*t70;
t110 = t108+t109-t116;
t111 = t3.*t22.*t110;
t115 = t3.*t20.*t107;
t112 = t104+t111-t115;
t120 = t11.*t34;
t121 = t3.*t22.*t25;
t122 = t3.*t20.*t28;
t123 = qd6+t120+t121+t122;
t124 = t7.*t48;
t127 = t9.*t58;
t132 = qd1.*t8.*9.8e-3;
t128 = t124+t127-t132;
t129 = t9.*t48;
t130 = qd1.*t10.*9.8e-3;
t134 = t7.*t58;
t131 = t129+t130-t134;
t133 = t8.*t128;
t135 = qd2.*t10.*(4.1e1./1.0e2);
t254 = t10.*t131;
t136 = t133+t135-t254;
t137 = t11.*2.105822393260846e-1;
t138 = t137+8.376447865216925e-2;
t139 = t22.*t56.*2.105822393260846e-1;
t140 = t11.*t138;
t141 = t139+t140+2.491822393260846e-1;
t142 = t3.*t18.*t20.*2.105822393260846e-1;
t143 = t3.*t11.*t15.*t22.*2.105822393260846e-1;
t146 = t3.*t15.*t138;
t144 = t142+t143-t146;
t145 = t7.*t141;
t151 = t9.*t144;
t147 = t145-t151;
t148 = t9.*t141;
t149 = t7.*t144;
t150 = t148+t149;
t152 = t34.*t112;
t153 = t28.*t81;
t154 = t152+t153;
t155 = t37.*t81;
t156 = t11.*t22.*t25;
t157 = t11.*t20.*t28;
t173 = t3.*t34;
t158 = t156+t157-t173;
t159 = t99.*t123.*2.105822393260846e-1;
t174 = t81.*t158.*2.105822393260846e-1;
t160 = t155+t159-t174;
t161 = t37.*t99;
t175 = t31.*t112;
t162 = t161-t175;
t163 = t25.*t81;
t164 = t34.*t99;
t165 = t163+t164;
t166 = t28.*t99;
t190 = t25.*t112;
t167 = t166-t190;
t168 = t20.*t25;
t195 = t22.*t28;
t169 = t168-t195;
t170 = t81.*t169.*2.105822393260846e-1;
t171 = t112.*t123.*2.105822393260846e-1;
t194 = t31.*t81;
t172 = t170+t171-t194;
t176 = t54.*t99;
t177 = t44.*t112;
t178 = t3.*t20.*t154.*2.105822393260846e-1;
t179 = t3.*t22.*t165.*2.105822393260846e-1;
t180 = t176+t177+t178+t179;
t181 = qd5.*t180;
t182 = qd6.*t3.*t160;
t183 = qd6.*t11.*t162;
t184 = t181+t182+t183;
t185 = t19.*t74;
t186 = t18.*t31.*t56;
t187 = qd1.*t9.*t10.*2.491822393260846e-1;
t188 = t138.*t165;
t189 = t3.*t31.*t112;
t191 = t3.*t20.*t167.*2.105822393260846e-1;
t221 = t54.*t81;
t192 = t188+t189+t191-t221;
t193 = qd5.*t192;
t196 = qd6.*t11.*t22.*t160;
t222 = qd6.*t20.*t172;
t223 = qd6.*t3.*t22.*t162;
t197 = t193+t196-t222-t223;
t198 = t19.*t86;
t199 = qd1.*t8.*t63;
t200 = t198+t199;
t201 = t3.*t15.*t20.*2.105822393260846e-1;
t202 = t3.*t18.*t138;
t203 = t15.*t54;
t204 = t11.*t18.*t44;
t205 = qd1.*t7.*t8.*2.491822393260846e-1;
t206 = -t186-t187+t203+t204+t205;
t207 = t44.*t81;
t208 = t3.*t31.*t99;
t209 = t3.*t22.*t167.*2.105822393260846e-1;
t236 = t138.*t154;
t210 = t207+t208+t209-t236;
t211 = qd5.*t210;
t212 = qd6.*t3.*t20.*t162;
t237 = qd6.*t22.*t172;
t238 = qd6.*t11.*t20.*t160;
t213 = t211+t212-t237-t238;
t214 = t19.*t103;
t215 = t17.*t91;
t216 = t214+t215;
t224 = t3.*t11.*t18.*t22.*2.105822393260846e-1;
t217 = t201+t202-t224;
t218 = t14.*t103;
t219 = t17.*t74;
t220 = t218+t219;
t233 = t14.*t91;
t225 = t185-t233;
t226 = qd1.*t8.*(4.1e1./1.0e2);
t227 = t8.*t150;
t228 = t10.*t147;
t261 = t10.*(4.1e1./1.0e2);
t229 = t227+t228-t261;
t230 = t201+t202-t224-9.8e-3;
t231 = t11.*t184;
t232 = t144.*t220;
t234 = t58.*t91;
t235 = t103.*t206;
t239 = t18.*t213;
t240 = t48.*t91;
t241 = t74.*t206;
t282 = t216.*t217;
t283 = t141.*t220;
t242 = t240+t241-t282-t283;
t243 = qd4.*t242;
t284 = t3.*t15.*t184;
t285 = t11.*t15.*t197;
t244 = t239+t243-t284-t285;
t245 = t19.*t72;
t246 = qd1.*t10.*t63;
t247 = t245+t246;
t248 = qd1.*t8.*t72;
t279 = qd1.*t10.*t86;
t249 = t248-t279;
t250 = t217.*t225;
t251 = t232+t234+t235+t250;
t252 = qd4.*t251;
t277 = t3.*t197;
t253 = t231+t252-t277;
t255 = t186+t187-t203-t204-t205+t226;
t256 = t15.*t213;
t257 = t10.*t128;
t258 = t8.*t131;
t259 = t257+t258-qd2.*t8.*(4.1e1./1.0e2);
t260 = t67.*t136;
t262 = qd2.*t67.*t229;
t263 = t8.*(4.1e1./1.0e2);
t264 = t10.*t150;
t303 = t8.*t147;
t265 = t263+t264-t303;
t266 = t260+t262-t60.*t259-qd2.*t60.*t265;
t267 = t86.*t128;
t268 = t147.*t247;
t269 = t150.*t200;
t270 = t267+t268+t269-t72.*t131;
t271 = t58.*t74;
t272 = t141.*t225;
t273 = t271+t272-t48.*t103-t144.*t216;
t274 = t3.*t18.*t184;
t275 = t11.*t18.*t197;
t276 = t256+t274+t275-qd2.*t266-qd3.*t270-qd4.*t273;
t278 = t63.*t128;
t280 = t147.*t249;
t300 = t200.*t230;
t301 = t72.*t206;
t281 = t278+t280-t300-t301;
t286 = t7.*t244;
t287 = t9.*t253;
t302 = qd3.*t281;
t288 = t286+t287-t302;
t289 = qd1.*t60.*t229;
t290 = qd2.*t60.*t230;
t291 = t230.*t247;
t292 = t63.*t131;
t293 = t150.*t249;
t305 = t86.*t206;
t294 = t291+t292+t293-t305;
t295 = qd3.*t294;
t296 = t217.*(t185-t233);
t297 = t232+t234+t235+t296;
t298 = qd4.*t297;
t299 = t231-t277+t298;
t304 = t7.*t299;
t306 = t295+t304-t9.*t244;
t307 = t99.*t169;
t308 = t112.*t158;
t309 = t307+t308;
t310 = t81.*t169;
t311 = t112.*t123;
t312 = t310+t311;
t313 = t99.*t123;
t319 = t81.*t158;
t314 = t313-t319;
t315 = qd6.*t11.*t309;
t316 = qd6.*t3.*t312;
t324 = qd5.*t167;
t317 = t315+t316-t324;
t318 = qd5.*t154;
t320 = qd6.*t11.*t22.*t312;
t321 = qd4.*t225;
t322 = qd5.*t165;
t323 = qd6.*t3.*t20.*t309;
t325 = t3.*t15.*t317;
t326 = qd6.*t20.*(t313-t319);
t329 = qd6.*t3.*t22.*t309;
t327 = t318+t320+t326-t329;
t328 = qd4.*t216;
t330 = t3.*t327;
t341 = t11.*t317;
t331 = t328+t330-t341;
t332 = qd6.*t22.*t314;
t334 = qd6.*t11.*t20.*t312;
t333 = t322+t323+t332-t334;
t335 = qd2.^2;
t336 = t67.*t335;
t337 = qd6.*t22.*(t313-t319);
t338 = t322+t323-t334+t337;
t339 = t11.*t15.*t327;
t340 = qd3.*t200;
t342 = qd3.*t247;
t343 = t9.*t331;
t344 = t15.*t338;
t345 = qd3.*t249;
t346 = qd4.*t220;
t347 = qd1.*qd2.*t60;
t348 = t3.*t18.*t317;
t349 = t11.*t18.*t327;
t350 = t344+t345+t346+t347+t348+t349;
t353 = t18.*t338;
t354 = t321+t325+t339-t353;
t351 = t7.*t354;
t352 = t342+t343+t351;
jacob_dot = [-t67.*(t8.*(t295-t9.*t244+t7.*t253)-t10.*t288+qd2.*(t289+t290+t67.*t255))+t60.*t276-qd1.*(t60.*t136+t67.*(t186+t187+t226-t15.*t54-qd1.*t7.*t8.*2.491822393260846e-1-t11.*t18.*t44));t67.*t276+t60.*(qd2.*(t289+t290+t67.*(t186+t187-t203-t204-t205+t226))-t10.*t288+t8.*t306)-qd1.*(t260-t60.*t255);-t10.*t306-t8.*(t286-t302+t9.*t299)-qd2.*(-t60.*t255+qd2.*t67.*t230+qd1.*t60.*t265);-t67.*(t336+t8.*(t340-t7.*t331+t9.*(t321+t325-t18.*t333+t11.*t15.*(t318+t320-t329+qd6.*t20.*t314)))+t10.*(t342+t343+t7.*(t321+t325+t339-t18.*t333)))+t60.*t350;t67.*t350+t60.*(t336+t10.*t352+t8.*(t340-t7.*t331+t9.*(t321+t325+t339-t18.*t338)));-t10.*(t340-t7.*t331+t9.*t354)+t8.*t352+t60.*t335];
