function T0_5 = T0_5(rob,in2)
%% T0_5 - Forward kinematics for the Jaco copy arm up to frame 5 of 6. 
% ========================================================================= 
%    
%    T = T0_5(rob,q) 
%    T = rob.T0_5(q) 
%    
%  Description:: 
%    Given a set of joint variables up to joint number 5 the function 
%    computes the pose belonging to that joint with respect to the base frame. 
%    
%  Input:: 
%    q:  5-element vector of generalized coordinates. 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    T:  [4x4] Homogenous transformation matrix relating the pose of joint 5 of 6 
%              for the given joint values to the base frame. 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also Jaco copy.
%    
    
% Copyright (C) 1993-2015, by Peter I. Corke 
% Copyright (C) 2012-2015, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    12-Aug-2015 17:22:20

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
t2 = cos(q1);
t3 = pi.*(1.0./2.0);
t4 = q3+t3;
t5 = q2-t3;
t6 = cos(t5);
t7 = sin(t4);
t8 = cos(t4);
t9 = sin(t5);
t10 = pi.*(1.1e1./3.6e1);
t11 = cos(q4);
t12 = sin(q1);
t13 = cos(t10);
t14 = sin(q4);
t15 = t2.*t7.*t9;
t16 = t2.*t6.*t8;
t17 = t15+t16;
t18 = sin(t10);
t19 = t2.*t6.*t7;
t26 = t2.*t8.*t9;
t20 = t19-t26;
t21 = sin(q5);
t22 = t12.*t14;
t23 = t11.*t17;
t24 = t22+t23;
t25 = cos(q5);
t27 = t18.*t20;
t28 = t11.*t12.*t13;
t33 = t13.*t14.*t17;
t29 = t27+t28-t33;
t30 = t13.*t20;
t31 = t14.*t17.*t18;
t32 = t30+t31-t11.*t12.*t18;
t34 = t6.*t8.*t12;
t35 = t7.*t9.*t12;
t36 = t34+t35;
t37 = t6.*t7.*t12;
t41 = t8.*t9.*t12;
t38 = t37-t41;
t39 = t2.*t14;
t49 = t11.*t36;
t40 = t39-t49;
t42 = t2.*t11.*t13;
t43 = t13.*t14.*t36;
t50 = t18.*t38;
t44 = t42+t43-t50;
t45 = t13.*t38;
t46 = t2.*t11.*t18;
t47 = t14.*t18.*t36;
t48 = t45+t46+t47;
t51 = t6.*t7;
t56 = t8.*t9;
t52 = t51-t56;
t53 = t6.*t8;
t54 = t7.*t9;
t55 = t53+t54;
t57 = t18.*t55;
t58 = t13.*t14.*t52;
t59 = t57+t58;
t60 = t13.*t55;
t61 = t60-t14.*t18.*t52;
T0_5 = reshape([-t24.*t25-t21.*t29,-t21.*t44-t25.*t40,-t21.*t59+t11.*t25.*t52,0.0,t18.*t32+t13.*t21.*t24-t13.*t25.*t29,-t18.*t48+t13.*t21.*t40-t13.*t25.*t44,t18.*t61-t13.*t25.*t59-t11.*t13.*t21.*t52,0.0,t13.*t32-t18.*t21.*t24+t18.*t25.*t29,-t13.*t48-t18.*t21.*t40+t18.*t25.*t44,t13.*t61+t18.*t25.*t59+t11.*t18.*t21.*t52,0.0,t12.*(-9.8e-3)+t2.*t6.*(4.1e1./1.0e2)-t13.*t20.*8.376447865216925e-2-t2.*t6.*t7.*2.491822393260846e-1+t2.*t8.*t9.*2.491822393260846e-1+t11.*t12.*t18.*8.376447865216925e-2-t14.*t17.*t18.*8.376447865216925e-2,t2.*(-9.8e-3)-t6.*t12.*(4.1e1./1.0e2)+t13.*t38.*8.376447865216925e-2+t6.*t7.*t12.*2.491822393260846e-1-t8.*t9.*t12.*2.491822393260846e-1+t2.*t11.*t18.*8.376447865216925e-2+t14.*t18.*t36.*8.376447865216925e-2,t9.*(4.1e1./1.0e2)-t6.*t8.*2.491822393260846e-1-t7.*t9.*2.491822393260846e-1-t13.*t55.*8.376447865216925e-2+t14.*t18.*t52.*8.376447865216925e-2+2.755e-1,1.0],[4, 4]);
