function T0_6 = T0_6(rob,in2)
%% T0_6 - Forward kinematics for the Jaco copy arm up to frame 6 of 6. 
% ========================================================================= 
%    
%    T = T0_6(rob,q) 
%    T = rob.T0_6(q) 
%    
%  Description:: 
%    Given a set of joint variables up to joint number 6 the function 
%    computes the pose belonging to that joint with respect to the base frame. 
%    
%  Input:: 
%    q:  6-element vector of generalized coordinates. 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    T:  [4x4] Homogenous transformation matrix relating the pose of joint 6 of 6 
%              for the given joint values to the base frame. 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also Jaco copy.
%    
    
% Copyright (C) 1993-2015, by Peter I. Corke 
% Copyright (C) 2012-2015, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    17-Aug-2015 15:23:51

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
t2 = cos(q1);
t3 = pi.*(1.0./2.0);
t4 = q3+t3;
t5 = q2-t3;
t6 = cos(t5);
t7 = sin(t4);
t8 = cos(t4);
t9 = pi.*(1.1e1./3.6e1);
t10 = cos(q4);
t11 = sin(q1);
t12 = cos(t9);
t13 = sin(q4);
t14 = sin(t5);
t15 = t2.*t6.*t8;
t16 = t2.*t7.*t14;
t17 = t15+t16;
t18 = pi.*(5.0./9.0);
t19 = q6+t18;
t20 = sin(t9);
t21 = t2.*t6.*t7;
t28 = t2.*t8.*t14;
t22 = t21-t28;
t23 = sin(q5);
t24 = t11.*t13;
t25 = t10.*t17;
t26 = t24+t25;
t27 = cos(q5);
t29 = t20.*t22;
t30 = t10.*t11.*t12;
t38 = t12.*t13.*t17;
t31 = t29+t30-t38;
t32 = cos(t19);
t33 = t12.*t22;
t34 = t13.*t17.*t20;
t44 = t10.*t11.*t20;
t35 = t33+t34-t44;
t36 = t20.*t35;
t37 = t12.*t23.*t26;
t39 = t36+t37-t12.*t27.*t31;
t40 = sin(t19);
t41 = t26.*t27;
t42 = t23.*t31;
t43 = t41+t42;
t45 = t6.*t8.*t11;
t46 = t7.*t11.*t14;
t47 = t45+t46;
t48 = t6.*t7.*t11;
t52 = t8.*t11.*t14;
t49 = t48-t52;
t50 = t2.*t13;
t61 = t10.*t47;
t51 = t50-t61;
t53 = t2.*t10.*t12;
t54 = t12.*t13.*t47;
t62 = t20.*t49;
t55 = t53+t54-t62;
t56 = t12.*t49;
t57 = t2.*t10.*t20;
t58 = t13.*t20.*t47;
t59 = t56+t57+t58;
t60 = t20.*t59;
t63 = t12.*t27.*t55;
t64 = t60+t63-t12.*t23.*t51;
t65 = t27.*t51;
t66 = t23.*t55;
t67 = t65+t66;
t68 = t6.*t8;
t69 = t7.*t14;
t70 = t68+t69;
t71 = t6.*t7;
t73 = t8.*t14;
t72 = t71-t73;
t74 = t20.*t70;
t75 = t12.*t13.*t72;
t76 = t74+t75;
t77 = t12.*t70;
t84 = t13.*t20.*t72;
t78 = t77-t84;
t79 = t12.*t27.*t76;
t80 = t10.*t12.*t23.*t72;
t81 = t79+t80-t20.*t78;
t82 = t23.*t76;
t83 = t82-t10.*t27.*t72;
T0_6 = reshape([-t32.*t43+t39.*t40,-t32.*t67-t40.*t64,-t32.*t83-t40.*t81,0.0,-t32.*t39-t40.*t43,t32.*t64-t40.*t67,t32.*t81-t40.*t83,0.0,-t12.*t35+t20.*t23.*t26-t20.*t27.*t31,t12.*t59+t20.*t23.*t51-t20.*t27.*t55,-t12.*t78-t20.*t27.*t76-t10.*t20.*t23.*t72,0.0,t11.*(-9.8e-3)+t2.*t6.*(4.1e1./1.0e2)-t12.*t22.*8.376447865216925e-2-t12.*t35.*2.105822393260846e-1-t2.*t6.*t7.*2.491822393260846e-1+t2.*t8.*t14.*2.491822393260846e-1+t10.*t11.*t20.*8.376447865216925e-2-t13.*t17.*t20.*8.376447865216925e-2+t20.*t23.*t26.*2.105822393260846e-1-t20.*t27.*t31.*2.105822393260846e-1,t2.*(-9.8e-3)-t6.*t11.*(4.1e1./1.0e2)+t12.*t49.*8.376447865216925e-2+t12.*t59.*2.105822393260846e-1+t6.*t7.*t11.*2.491822393260846e-1+t2.*t10.*t20.*8.376447865216925e-2-t8.*t11.*t14.*2.491822393260846e-1+t13.*t20.*t47.*8.376447865216925e-2+t20.*t23.*t51.*2.105822393260846e-1-t20.*t27.*t55.*2.105822393260846e-1,t14.*(4.1e1./1.0e2)-t6.*t8.*2.491822393260846e-1-t7.*t14.*2.491822393260846e-1-t12.*t70.*8.376447865216925e-2-t12.*t78.*2.105822393260846e-1+t13.*t20.*t72.*8.376447865216925e-2-t20.*t27.*t76.*2.105822393260846e-1-t10.*t20.*t23.*t72.*2.105822393260846e-1+2.755e-1,1.0],[4, 4]);
