/*! \file Puma560_jacobn.h
\brief C code for the Jacobian with respect to the end-effector coordinate frame of the Puma 560 copy arm. 
    
  
Given a full set of joint variables the function 
computes the robot jacobian with respect to the end-effector frame. Angles have to be given in radians! 
    
__Example__:<BR> 
     
    
__Known Bugs__:<BR> 
  
    
__TODO__:<BR> 
  
    
__References__:<BR> 
+ Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
+ Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
+ Introduction to Robotics, Mechanics and Control - Craig 
+ Modeling, Identification & Control of Robots - Khalil & Dombre 
    
__Authors__:<BR> 
This is an autogenerated function!Code generator written by:Joern Malzahn (joern.malzahn@tu-dortmund.de)    
<BR><BR> 
__Copyright Note__: 
  <BR>Copyright  (C) 1993-2014, by Peter I. Corke 
  <BR>Copyright  (C) 2012-2014, by Joern Malzahn 
  
  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
  
  RTB and code generated with RTB is free software: you can redistribute it and/or modify 
  it under the terms of the GNU Lesser General Public License as published by 
  the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version. 
   
  RTB is distributed in the hope that it will be useful, 
  but WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU Lesser General Public License for more details. 
   
  You should have received a copy of the GNU Leser General Public License 
  along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
  
  http://www.petercorke.com 
  
  The code generation module emerged during the work on a project funded by 
  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
  acknowledge the financial support. 
*/
    
/*!\fn void Puma560_jacobn(double Jn[][6], const double* input1);
\param input1:  6-element vector of generalized coordinates.
\param Jn:  [6x6] Jacobian matrix
*/


#include "Puma560_jacobn.h"

void Puma560_jacobn(double Jn[][6], const double* input1){
 
  double q1 = input1[0];
  double q2 = input1[1];
  double q3 = input1[2];
  double q4 = input1[3];
  double q5 = input1[4];
  double q6 = input1[5];
 
                                     Jn[0][0]=0;
 Jn[1][0]=0;
 Jn[2][0]=0;
 Jn[3][0]=0;
 Jn[4][0]=0;
 Jn[5][0]=0;
 Jn[0][1]=0;
 Jn[1][1]=0;
 Jn[2][1]=0;
 Jn[3][1]=0;
 Jn[4][1]=0;
 Jn[5][1]=0;
 Jn[0][2]=0;
 Jn[1][2]=0;
 Jn[2][2]=0;
 Jn[3][2]=0;
 Jn[4][2]=0;
 Jn[5][2]=0;
 Jn[0][3]=0;
 Jn[1][3]=0;
 Jn[2][3]=0;
 Jn[3][3]=0;
 Jn[4][3]=0;
 Jn[5][3]=0;
 Jn[0][4]=0;
 Jn[1][4]=0;
 Jn[2][4]=0;
 Jn[3][4]=0;
 Jn[4][4]=0;
 Jn[5][4]=0;
 Jn[0][5]=0;
 Jn[1][5]=0;
 Jn[2][5]=0;
 Jn[3][5]=0;
 Jn[4][5]=0;
 Jn[5][5]=0;



  Jn[0][0] = cos(q2+q3)*cos(q4)*sin(q6)*2.03E-2-sin(q2+q3)*cos(q4)*sin(q6)*4.318E-1+cos(q2)*cos(q4)*sin(q6)*4.318E-1+cos(q2+q3)*cos(q5)*cos(q6)*sin(q4)*2.03E-2-sin(q2+q3)*cos(q5)*cos(q6)*sin(q4)*4.318E-1+cos(q2)*cos(q5)*cos(q6)*sin(q4)*4.318E-1-cos(q2)*cos(q3)*sin(q4)*sin(q6)*1.5005E-1-cos(q2)*cos(q6)*sin(q3)*sin(q5)*1.5005E-1-cos(q3)*cos(q6)*sin(q2)*sin(q5)*1.5005E-1+sin(q2)*sin(q3)*sin(q4)*sin(q6)*1.5005E-1+cos(q2)*cos(q3)*cos(q4)*cos(q5)*cos(q6)*1.5005E-1-cos(q4)*cos(q5)*cos(q6)*sin(q2)*sin(q3)*1.5005E-1;
  Jn[0][1] = cos(q2+q3)*cos(q4)*cos(q6)*2.03E-2-sin(q2+q3)*cos(q4)*cos(q6)*4.318E-1+cos(q2)*cos(q4)*cos(q6)*4.318E-1-cos(q2+q3)*cos(q5)*sin(q4)*sin(q6)*2.03E-2+sin(q2+q3)*cos(q5)*sin(q4)*sin(q6)*4.318E-1-cos(q2)*cos(q3)*cos(q6)*sin(q4)*1.5005E-1-cos(q2)*cos(q5)*sin(q4)*sin(q6)*4.318E-1+cos(q6)*sin(q2)*sin(q3)*sin(q4)*1.5005E-1+cos(q2)*sin(q3)*sin(q5)*sin(q6)*1.5005E-1+cos(q3)*sin(q2)*sin(q5)*sin(q6)*1.5005E-1-cos(q2)*cos(q3)*cos(q4)*cos(q5)*sin(q6)*1.5005E-1+cos(q4)*cos(q5)*sin(q2)*sin(q3)*sin(q6)*1.5005E-1;
  Jn[0][2] = cos(q2)*cos(q5)*sin(q3)*(-1.5005E-1)-cos(q3)*cos(q5)*sin(q2)*1.5005E-1-cos(q2)*sin(q4)*sin(q5)*4.318E-1-cos(q2)*cos(q3)*cos(q4)*sin(q5)*1.5005E-1-cos(q2)*cos(q3)*sin(q4)*sin(q5)*2.03E-2+cos(q2)*sin(q3)*sin(q4)*sin(q5)*4.318E-1+cos(q3)*sin(q2)*sin(q4)*sin(q5)*4.318E-1+cos(q4)*sin(q2)*sin(q3)*sin(q5)*1.5005E-1+sin(q2)*sin(q3)*sin(q4)*sin(q5)*2.03E-2;
  Jn[0][3] = -cos(q2)*(sin(q3)*(sin(q4)*sin(q6)-cos(q4)*cos(q5)*cos(q6))-cos(q3)*cos(q6)*sin(q5))-sin(q2)*(cos(q3)*(sin(q4)*sin(q6)-cos(q4)*cos(q5)*cos(q6))+cos(q6)*sin(q3)*sin(q5));
  Jn[0][4] = -cos(q2)*(sin(q3)*(cos(q6)*sin(q4)+cos(q4)*cos(q5)*sin(q6))+cos(q3)*sin(q5)*sin(q6))-sin(q2)*(cos(q3)*(cos(q6)*sin(q4)+cos(q4)*cos(q5)*sin(q6))-sin(q3)*sin(q5)*sin(q6));
  Jn[0][5] = cos(q2)*(cos(q3)*cos(q5)-cos(q4)*sin(q3)*sin(q5))-sin(q2)*(cos(q5)*sin(q3)+cos(q3)*cos(q4)*sin(q5));
  Jn[1][0] = cos(q6)*sin(q5)*2.03E-2+sin(q4)*sin(q6)*4.318E-1-sin(q3)*sin(q4)*sin(q6)*4.318E-1-cos(q4)*cos(q5)*cos(q6)*4.318E-1+cos(q3)*cos(q6)*sin(q5)*4.318E-1+cos(q4)*cos(q5)*cos(q6)*sin(q3)*4.318E-1;
  Jn[1][1] = cos(q6)*sin(q4)*4.318E-1-sin(q5)*sin(q6)*2.03E-2+cos(q4)*cos(q5)*sin(q6)*4.318E-1-cos(q6)*sin(q3)*sin(q4)*4.318E-1-cos(q3)*sin(q5)*sin(q6)*4.318E-1-cos(q4)*cos(q5)*sin(q3)*sin(q6)*4.318E-1;
  Jn[1][2] = cos(q5)*2.03E-2+cos(q3)*cos(q5)*4.318E-1+cos(q4)*sin(q5)*4.318E-1-cos(q4)*sin(q3)*sin(q5)*4.318E-1;
  Jn[1][3] = -cos(q4)*sin(q6)-cos(q5)*cos(q6)*sin(q4);
  Jn[1][4] = -cos(q4)*cos(q6)+cos(q5)*sin(q4)*sin(q6);
  Jn[1][5] = sin(q4)*sin(q5);
  Jn[2][0] = cos(q6)*sin(q5)*2.03E-2+sin(q4)*sin(q6)*4.318E-1-cos(q4)*cos(q5)*cos(q6)*4.318E-1;
  Jn[2][1] = cos(q6)*sin(q4)*4.318E-1-sin(q5)*sin(q6)*2.03E-2+cos(q4)*cos(q5)*sin(q6)*4.318E-1;
  Jn[2][2] = cos(q5)*2.03E-2+cos(q4)*sin(q5)*4.318E-1;
  Jn[2][3] = -cos(q4)*sin(q6)-cos(q5)*cos(q6)*sin(q4);
  Jn[2][4] = -cos(q4)*cos(q6)+cos(q5)*sin(q4)*sin(q6);
  Jn[2][5] = sin(q4)*sin(q5);
  Jn[3][3] = cos(q6)*sin(q5);
  Jn[3][4] = -sin(q5)*sin(q6);
  Jn[3][5] = cos(q5);
  Jn[4][3] = -sin(q6);
  Jn[4][4] = -cos(q6);
  Jn[5][5] = 1.0;
}
 

