/*! \file accel.h
\brief C-implementation of the forward dynamics for the LBR4p copy arm. 
    
  
Given a full set of joint angles and velocities 
this function computes the joint space accelerations effected by the generalized forces. Angles have to be given in radians! 
    
__Example__:<BR> 
     
    
__Known Bugs__:<BR> 
  
    
__TODO__:<BR> 
  
    
__References__:<BR> 
+ Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
+ Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
+ Introduction to Robotics, Mechanics and Control - Craig 
+ Modeling, Identification & Control of Robots - Khalil & Dombre 
    
__Authors__:<BR> 
This is an autogenerated function!Code generator written by:Joern Malzahn (joern.malzahn@tu-dortmund.de)    
<BR><BR> 
__Copyright Note__: 
  <BR>Copyright  (C) 1993-2014, by Peter I. Corke 
  <BR>Copyright  (C) 2012-2014, by Joern Malzahn 
  
  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
  
  RTB and code generated with RTB is free software: you can redistribute it and/or modify 
  it under the terms of the GNU Lesser General Public License as published by 
  the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version. 
   
  RTB is distributed in the hope that it will be useful, 
  but WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU Lesser General Public License for more details. 
   
  You should have received a copy of the GNU Leser General Public License 
  along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
  
  http://www.petercorke.com 
  
  The code generation module emerged during the work on a project funded by 
  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
  acknowledge the financial support. 
*/
    
/*!\fn 
\param input1:  7-element vector of generalized coordinates
\param input2:  7-element vector of generalized velocities
\param input3:  [7x1] vector of generalized forces.
\param QDD:  7-element output vector of generalized accelerations.
*/

#include "mex.h"
#include "LBR4p_accel.h"


/* The gateway function */
void mexFunction( int nlhs, mxArray *plhs[],
        int nrhs, const mxArray *prhs[])
{
	/* variable declarations */
	double* outMatrix;      /* output matrix */
	double* input1;
	double* input2;
	double* input3;
 
	/* check for proper number of arguments */
	if(nrhs!=4) {
		mexErrMsgIdAndTxt("LBR4p_accel:nrhs",
		                       "3 inputs required.");
	}
	if(nlhs>1) {
		mexErrMsgIdAndTxt("LBR4p_accel:nlhs",
		                       "Only single output allowed.");
	}
 
	/* allocate memory for the output matrix */
	plhs[0] = mxCreateDoubleMatrix(7,1, mxREAL);
	/* get a pointer to the real data in the output matrix */
	outMatrix = mxGetPr(plhs[0]);
 
	/* get a pointers to the real data in the input matrices */
	input1 = mxGetPr(prhs[1]);
	input2 = mxGetPr(prhs[2]);
	input3 = mxGetPr(prhs[3]);
 
	/* call the computational routine */
	LBR4p_accel(outMatrix, input1, input2, input3);
}
