function Irow = inertia_row_7(rob,in2)
%% INERTIA_ROW_7 - Computation of the robot specific inertia matrix row for corresponding to joint 7 of 7. 
% ========================================================================= 
%    
%    Irow = inertia_row_7(rob,q) 
%    Irow = rob.inertia_row_7(q) 
%    
%  Description:: 
%    Given a full set of joint variables this function computes the 
%    inertia matrix row number 7 of 7 for LBR4p copy. 
%    
%  Input:: 
%    rob: robot object of LBR4p copy specific class 
%    q:  7-element vector of generalized 
%         coordinates 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Irow:  [1x7] row of the robot inertia matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2015, by Peter I. Corke 
% Copyright (C) 2012-2015, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    05-Aug-2015 00:19:30

q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
t2 = cos(q6);
t3 = sin(q4);
t4 = cos(q4);
t5 = cos(q5);
t6 = sin(q6);
t7 = sin(q3);
t8 = t2.*t3.*1.584375e-4;
t9 = t4.*t5.*t6.*1.584375e-4;
t10 = t8+t9;
t11 = cos(q3);
t12 = sin(q5);
t13 = t2.*t4.*1.584375e-4;
t14 = t13-t3.*t5.*t6.*1.584375e-4;
Irow = [-sin(q2).*(t10.*t11-t6.*t7.*t12.*1.584375e-4)+t14.*cos(q2),t7.*t10+t6.*t11.*t12.*1.584375e-4,t14,t6.*t12.*1.584375e-4,t2.*1.584375e-4,0.0,1.94222943168e-1];
