/*! \file gaussjordan.h
\brief Compute the inverse of a positive definite square matrix 
    
  
Given a positive definite square matrix of dimension dim in inMatrix, 
the function returns its inverse outMatrix. The inverse is computed using Gauss-Jordan elimination  
without pivoting. 
    
__Example__:<BR> 
     
    
__Known Bugs__:<BR> 
  
    
__TODO__:<BR> 
  
    
__References__:<BR> 
+ The C Book: http://publications.gbdirect.co.uk/c_book/ 
    
__Authors__:<BR> 
This is an autogenerated function!Code generator written by:Joern Malzahn (joern.malzahn@tu-dortmund.de)    
<BR><BR> 
__Copyright Note__: 
  <BR>Copyright  (C) 1993-2016, by Peter I. Corke 
  <BR>Copyright  (C) 2012-2016, by Joern Malzahn 
  
  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
  
  RTB and code generated with RTB is free software: you can redistribute it and/or modify 
  it under the terms of the GNU Lesser General Public License as published by 
  the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version. 
   
  RTB is distributed in the hope that it will be useful, 
  but WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU Lesser General Public License for more details. 
   
  You should have received a copy of the GNU Leser General Public License 
  along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
  
  http://www.petercorke.com 
  
  The code generation module emerged during the work on a project funded by 
  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
  acknowledge the financial support. 
*/
    
/*!\fn gaussjordan(const double* inMatrix, double* outMatrix, int dim)
\param inMatrix: array of doubles storing [dim x dim] elements of the input square matrix column by column,
\param dim: dimension of the square matrix.
\param outMatrix: array of doubles storing [dim x dim] elements of the output square matrix column by column.
*/


#ifndef GAUSSJORDAN_H
#define GAUSSJORDAN_H

void gaussjordan(const double *inMatrix, double *outMatrix, int dim);

#endif /*GAUSSJORDAN_H */
