/*! \file LBR4pSimple_accel.h
\brief C-implementation of the forward dynamics for the LBR4pSimple copy arm. 
    
  
Given a full set of joint angles and velocities 
this function computes the joint space accelerations effected by the generalized forces. Angles have to be given in radians! 
    
__Example__:<BR> 
     
    
__Known Bugs__:<BR> 
  
    
__TODO__:<BR> 
  
    
__References__:<BR> 
+ Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
+ Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
+ Introduction to Robotics, Mechanics and Control - Craig 
+ Modeling, Identification & Control of Robots - Khalil & Dombre 
    
__Authors__:<BR> 
This is an autogenerated function!Code generator written by:Joern Malzahn (joern.malzahn@tu-dortmund.de)    
<BR><BR> 
__Copyright Note__: 
  <BR>Copyright  (C) 1993-2016, by Peter I. Corke 
  <BR>Copyright  (C) 2012-2016, by Joern Malzahn 
  
  This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
  
  RTB and code generated with RTB is free software: you can redistribute it and/or modify 
  it under the terms of the GNU Lesser General Public License as published by 
  the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version. 
   
  RTB is distributed in the hope that it will be useful, 
  but WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU Lesser General Public License for more details. 
   
  You should have received a copy of the GNU Leser General Public License 
  along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
  
  http://www.petercorke.com 
  
  The code generation module emerged during the work on a project funded by 
  the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
  acknowledge the financial support. 
*/
    
/*!\fn void LBR4pSimple_accel(double QDD[][7], const double* input1, const double* input2, const double* input3);
\param input1:  7-element vector of generalized coordinates
\param input2:  7-element vector of generalized velocities
\param input3:  [7x1] vector of generalized forces.
\param QDD:  7-element output vector of generalized accelerations.
*/


#ifndef LBR4PSIMPLE_ACCEL_H
#define LBR4PSIMPLE_ACCEL_H

#include "matvecprod.h"
#include "gaussjordan.h"
#include "LBR4pSimple_inertia.h"
#include "LBR4pSimple_coriolis.h"
#include "LBR4pSimple_gravload.h"
#include "LBR4pSimple_friction.h"

void LBR4pSimple_accel(double QDD[][7], const double* input1, const double* input2, const double* input3);

#endif /*LBR4PSIMPLE_ACCEL_H */
